#!/bin/sh
#
# Usage: c
# Description: opens the current directory in VSCode Editor
#
# Usage: c <directory>
# Description: opens the specified directory in VSCode Editor
#

if [ $# -eq 0 ]; then
  code .;
else
  code "$@";
fi;
