#!/bin/zsh
#
# Usage: fdp [directory]
# Description: fzfを使用して親ディレクトリに素早く移動する
#
# 現在のディレクトリから親ディレクトリを辿り、fzfで選択して移動します
function fdp() {
  local declare dirs=()
  get_parent_dirs() {
    if [[ -d "${1}" ]]; then dirs+=("$1"); else return; fi
    if [[ "${1}" == '/' ]]; then
      for _dir in "${dirs[@]}"; do echo $_dir; done
    else
      get_parent_dirs $(dirname "$1")
    fi
  }
  myrealpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
  }
  local DIR=$(get_parent_dirs $(myrealpath "${1:-$PWD}") | fzf-tmux --tac --preview 'exa -l {}')
  cd "$DIR"
}