#!/bin/zsh
#
# Usage: gbdfzf
# Description: fzfを使用してブランチをインタラクティブに削除する
#
# ローカルブランチをfzfで選択してgit branch -Dを実行します
function gbdfzf() {
  local branches branch
  branches=$(git branch -vv) &&
  branch=$(echo "$branches" | fzf -m) &&
  git branch -D $(echo "$branch" | awk '{print $1}' | sed "s/.* //")
}