#!/bin/zsh
#
# Go to a <repo> in ~/Code
#

goto() {
  GO_DEFAULT=sendgrid

  #
  # The brains behind goto
  #

  nav() {
    cd ~/Code/src/github.com/$1 &> /dev/null ||
    clone $1 2> /dev/null ||
    echo "repo @ $1 does not exist"
  }

  if hash complete 2>/dev/null; then
    complete -o default -o nospace -F _goto goto
  fi

  if hash shopt 2>/dev/null; then
    shopt -s cdspell
  fi

  case $1 in

    */*)
      nav $1
    ;;

    *)
      nav $GO_DEFAULT/$1
    ;;

  esac

  if hash shopt 2>/dev/null; then
    shopt -s cdspell
  fi

}