cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'oven-sh/bun'

brew 'aria2'
brew 'bat'
brew 'git'
brew 'git-delta'
brew 'lynx'
brew 'mas'
brew 'hub'
brew 'jless'
brew 'imagemagick'
brew 'mutt'
brew 'newsboat'
brew 'pure'
brew 'ripgrep'
brew 'tree'
brew 'urlview'
brew 'wget'
brew 'ripgrep'
brew 'webp'
brew 'tree'
brew 'zsh'
brew 'zsh-autosuggestions'
brew 'zsh-completions'
brew 'zsh-syntax-highlighting'
brew 'oven-sh/bun/bun'

cask '1password'
cask 'anki'
cask 'chromium'
cask 'inkscape'
cask 'alacritty'
cask 'keka'
cask 'librewolf'
cask 'licecap'
cask 'raycast'
cask 'spotify'
cask 'thinkorswim'
cask 'visual-studio-code'
cask 'qlcolorcode'
cask 'qlmarkdown'
cask 'qlstephen'
cask 'quicklook-json'
cask 'webpquicklook'
cask 'qlvideo'