cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'

brew 'coreutils'
brew 'git'
brew 'jq'
brew 'node'
brew 'openssl'
brew 'postgresql'
brew 'pyenv'
brew 'readline'
brew 'sbt'
brew 'scala'
brew 'the_silver_searcher'
brew 'tmux'

cask 'firefox'
cask 'intellij-idea'
cask 'iterm2'
cask 'google-chrome'
cask 'slack'
cask 'spotify'
cask 'sublime'
