#!/bin/sh

# write sane gnome 3 defaults

# workspaces span monitors (otherwise one is static)
gsettings set org.gnome.shell.overrides workspaces-only-on-primary false
# prevent alt-tab from showing apps on all workspaces
gsettings set org.gnome.shell.app-switcher current-workspace-only true
# disable animations - speeds up workspace switching
gsettings set org.gnome.desktop.interface enable-animations "false"

# add repos
add-apt-repository ppa:webupd8team/atom
add-apt-repository ppa:webupd8team/sublime-text-3

# spotify
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys BBEBDCB318AD50EC6865090613B00F1FD2C19886
echo deb http://repository.spotify.com stable non-free | sudo tee /etc/apt/sources.list.d/spotify.list
sudo apt update

apt update

sudo apt install -y atom calibre chromium-browser keepassx spotify-client tmux vim virtualbox

# discord
sudo apt install -y libc++1
wget -O discord.deb https://discordapp.com/api/download?platform=linux&format=deb
sudo dpkg -i discord.deb
rm discord.deb

# for mutt
sudo apt install -y mutt elinks

# install packages for atom
apm install minimap

# install rust
curl https://sh.rustup.rs -sSf | sh

# remove junk
sudo apt remove aisleriot cheese gnome-clocks gnome-dictionary gnome-mahjongg gnome-mines gnome-nibbles gnome-robots gnome-sound-recorder gnome-sudoku hitori swell-foop
sudo apt autoremove

cd script
./bootstrap

sudo apt install steam
