<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>gogo</string>
	</array>
	<key>name</key>
	<string>GoTPL: go</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.go</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.gotemplate</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.gogo</string>
	<key>uuid</key>
	<string>883ac00d-0e32-4abd-a9ef-a875d01c5d00</string>
</dict>
</plist>
