<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>gojava</string>
	</array>
	<key>name</key>
	<string>GoTPL: Java</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.java</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.gotemplate</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.gojava</string>
	<key>uuid</key>
	<string>8f35bafd-8c25-4b10-934f-e71e7bfd82da</string>
</dict>
</plist>
