<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>gojs</string>
	</array>
	<key>name</key>
	<string>GoTPL: js</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.js</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.gotemplate</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.gojs</string>
	<key>uuid</key>
	<string>d4cb8bec-4c89-4c86-b5c8-ef1c52370929</string>
</dict>
</plist>
