<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>gojson</string>
	</array>
	<key>name</key>
	<string>GoSublime: JSON</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.json</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.gotemplate</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.gojson</string>
	<key>uuid</key>
	<string>e256ab58-6e47-11e8-adc0-fa7ae01bbebc</string>
</dict>
</plist>
