<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>gots</string>
	</array>
	<key>name</key>
	<string>GoTPL: ts</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.ts</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.gotemplate</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.gots</string>
	<key>uuid</key>
	<string>ebea436b-f1ed-4b70-a1d1-b34aaa2ed542</string>
</dict>
</plist>
