#!/bin/sh
set -e
PATH="$HOME/bin:/usr/local/bin:$PATH"

mkdir .git/tags_lock 2>/dev/null || exit 0
trap 'rmdir .git/tags_lock; if [ -f .git/tags.$$  ]; then rm .git/tags.$$; fi' EXIT

# Assumes universal-ctags is on the path
ctags --tag-relative=yes -R -f .git/tags.$$ --languages=-sql --exclude=node_modules
--exclude=vendor --exclude=log --exclude=.git
mv .git/tags.$$ .git/tags
