#!/bin/sh
# Setup a machine for Sublime Text 2
set -x

# symlink settings in
sublime_dir=~/Library/Application\ Support/Sublime\ Text\ 2/Packages
mv "$sublime_dir/User" "$sublime_dir/User.backup"
ln -s "$ZSH/sublime2/User" "$sublime_dir"

# Grab the Soda theme
cd ~/Library/Application\ Support/Sublime\ Text\ 2/Packages
git clone https://github.com/buymeasoda/soda-theme/ "Theme - Soda"
