#!/usr/bin/osascript
#
# A small command line script to make caps and esc key
#
# This exists because apple makes it too hard to do with default read
#
# Steps to make more like this Automator Record - Copy Paste to Script Editor

-- Launch System preferences
tell application "System Preferences" to activate

-- Click the “Keyboard” button.
delay 0.5
set timeoutSeconds to 2.0
set uiScript to "click UI Element \"Keyboard\" of scroll area 1 of window \"System Preferences\" of application process \"System Preferences\""
my doWithTimeout(uiScript, timeoutSeconds)

-- Click the “Modifier Keys…” button.
delay 0.5
set timeoutSeconds to 2.0
set uiScript to "click UI Element 15 of tab group 1 of window \"Keyboard\" of application process \"System Preferences\""
my doWithTimeout(uiScript, timeoutSeconds)

-- Make a selection from the popupbutton.
delay 0.5
set timeoutSeconds to 2.0
set uiScript to "click pop up button 2 of sheet 1 of window \"Keyboard\" of application process \"System Preferences\""
my doWithTimeout(uiScript, timeoutSeconds)

-- ⎋ Escape
delay 0.5
set timeoutSeconds to 2.0
set uiScript to "click menu item 5 of menu 1 of pop up button 2 of sheet 1 of window \"Keyboard\" of application process \"System Preferences\""
my doWithTimeout(uiScript, timeoutSeconds)

-- Click the “OK” button.
delay 0.5
set timeoutSeconds to 2.0
set uiScript to "click UI Element \"OK\" of sheet 1 of window \"Keyboard\" of application process \"System Preferences\""
my doWithTimeout(uiScript, timeoutSeconds)

on doWithTimeout(uiScript, timeoutSeconds)
	set endDate to (current date) + timeoutSeconds
	repeat
		try
			run script "tell application \"System Events\"
" & uiScript & "
end tell"
			exit repeat
		on error errorMessage
			if ((current date) > endDate) then
				error "Can not " & uiScript
			end if
		end try
	end repeat
end doWithTimeout

-- Quit
tell application "System Preferences" to quit
