# Brewfile

# Install command-line tools using Homebrew.

# Tap sources
# ================
tap "phinze/cask"
tap "homebrew/cask-fonts"


# Install formulae
# ================
# install cask formulae:
# install custom powerline fonts for dev and terminal
cask "font-menlo-for-powerline"
cask "font-fira-mono-for-powerline"
cask "font-source-code-pro-for-powerline"
cask "font-powerline-symbols"
cask "font-fira-code"

cask "iterm2"
cask "google-chrome"
cask "visual-studio-code"
cask "slack"
cask "docker"
cask "spectacle"
cask "alfred"
cask "charles"
cask "firefox"
cask "spotify"

# install brew formulae
brew "git-flow"
brew "git"
brew "watchman"
brew "wget"
brew "yarn"
brew "zlib"
brew "zsh"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
