alias zd="cd ~/Code/zendesk"
alias classic="cd ~/Code/zendesk/zendesk"
alias carson="cd ~/Code/zendesk/zendesk_carson"
alias console="cd ~/Code/zendesk/zendesk_console"
alias lotus="cd ~/Code/zendesk/zendesk_console"
alias market="cd ~/Code/zendesk/zendesk_app_market"
