export PATH="/usr/local/bin:/usr/local/sbin:$ZSH/bin:$PATH"
#export PATH="$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools"
export PATH="/usr/local/opt/python/libexec/bin:$PATH:$PYTHON_USER_DIR"
export PATH="$PATH:$HOME/.rvm/bin"
export PATH="$PATH:$HOME/.symfony/bin"
export PATH="$PATH:/usr/local/opt/sqlite/bin"
export PATH="$PATH:/Applications/PhpStorm.app/Contents/MacOS"
export PATH="$PATH:$HOME/Jobs/Tests/micmac/src/bin"