#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

if [ "$(uname -s)" == "Darwin" ]
then
  # Run Homebrew through the Brewfile
  echo "› brew bundle"
  brew bundle
fi

if [ "$(uname)" == "Linux" ]; then
  echo "› sudo apt install"
  grep -vE "^\s*#" Aptfile  | tr "\n" " " | xargs sudo apt install
fi

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
