#!/bin/sh
IFS=$'\n'

# Copies a few key files to a mounted partition.
#
# I use Time Machine for backups, but I also wanted to build out an
# offsite backup with my critical nonreplaceable data (photos, documents,
# etc). Since it's mobile, encryption is a plus (which Time Machine
# doesn't easily do). I create an encrypted sparsebundle on a tiny USB
# drive and do it to it.


# Your sparsebundle. I named mine "fuckplanets" because really, fuck planets.
sparsebundle="/Volumes/fuckplanets/backup.sparsebundle"

# Your destination. My sparsebundle mounts to "backup".
backup_location="/Volumes/backup"

# Directories to backup. Recursive, implied home (~) location.
directories=(
  Code
  Documents
  "Library/Application Support/Adium 2.0"
  Movies
  Music
  Pictures
)



hdiutil attach -noverify $sparsebundle

for directory in ${directories[@]}
  do
    rsync -avh --progress --delete ~/$directory $backup_location
done

hdiutil detach $backup_location
diskutil eject fuckplanets
