<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>slim</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^\s*([-%#\:\.\w\=].*)\s$</string>
	<key>foldingStopMarker</key>
	<string>^\s*$</string>
	<key>keyEquivalent</key>
	<string>^~S</string>
	<key>name</key>
	<string>Ruby Slim</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.prolog.slim</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(! )($|\s.*)</string>
			<key>name</key>
			<string>meta.prolog.slim</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.comment.slim</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^ *(/)\s*\S.*$\n?</string>
			<key>name</key>
			<string>comment.line.slash.slim</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^( *)(/)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.comment.slim</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!\1  )</string>
			<key>name</key>
			<string>comment.block.slim</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.slim</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(?===|=|-|~)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rubyline</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#inline-html-tag</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#normal-html-tag</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#embedded-ruby</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*([\w.#_-]*[\w]+)\s*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.slim</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$|(?!\.|#|\{|\[|=|-|~|/)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\{(?=.*\}|.*\|\s*$)</string>
					<key>end</key>
					<string>\}|$|^(?!.*\|\s*$)</string>
					<key>name</key>
					<string>meta.section.attributes.slim</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.ruby.rails</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#continuation</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\[(?=.*\]|.*\|\s*$)</string>
					<key>end</key>
					<string>\]|$|^(?!.*\|\s*$)</string>
					<key>name</key>
					<string>meta.section.object.slim</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.ruby.rails</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#continuation</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#rubyline</string>
				</dict>
				<dict>
					<key>match</key>
					<string>/</string>
					<key>name</key>
					<string>punctuation.terminator.tag.slim</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.escape.slim</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(\\.)</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(?=\||')</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#embedded-ruby</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>continuation</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.continuation.slim</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\\)\s*\n</string>
		</dict>
		<key>delimited-ruby-a</key>
		<dict>
			<key>begin</key>
			<string>=\(</string>
			<key>end</key>
			<string>\)(?=( \w|$))</string>
			<key>name</key>
			<string>source.ruby.embedded.slim</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ruby.rails</string>
				</dict>
			</array>
		</dict>
		<key>delimited-ruby-b</key>
		<dict>
			<key>begin</key>
			<string>=\[</string>
			<key>end</key>
			<string>\](?=( \w|$))</string>
			<key>name</key>
			<string>source.ruby.embedded.slim</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ruby.rails</string>
				</dict>
			</array>
		</dict>
		<key>delimited-ruby-c</key>
		<dict>
			<key>begin</key>
			<string>=\{</string>
			<key>end</key>
			<string>\}(?=( \w|$))</string>
			<key>name</key>
			<string>source.ruby.embedded.slim</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ruby.rails</string>
				</dict>
			</array>
		</dict>
		<key>embedded-ruby</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\\)#{</string>
			<key>end</key>
			<string>}</string>
			<key>name</key>
			<string>source.ruby.embedded.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ruby.rails</string>
				</dict>
			</array>
		</dict>
		<key>entities</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.html</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.html</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(&amp;)([a-zA-Z0-9]+|#[0-9]+|#x[0-9a-fA-F]+)(;)</string>
					<key>name</key>
					<string>constant.character.entity.html</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&amp;</string>
					<key>name</key>
					<string>invalid.illegal.bad-ampersand.html</string>
				</dict>
			</array>
		</dict>
		<key>inline-html-tag</key>
		<dict>
			<key>begin</key>
			<string>\s*([\w.#_-]+:)(?=\s)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.slim</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#normal-inline-html-tag</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag-stuff</string>
				</dict>
			</array>
		</dict>
		<key>interpolated-ruby</key>
		<dict>
			<key>begin</key>
			<string>=(?=\b)</string>
			<key>end</key>
			<string>\s|\w$</string>
			<key>name</key>
			<string>source.ruby.embedded.html</string>
		</dict>
		<key>normal-html-tag</key>
		<dict>
			<key>begin</key>
			<string>([\w.#_-]+=)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.slim</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-stuff</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-double-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-single-quoted</string>
				</dict>
			</array>
		</dict>
		<key>normal-inline-html-tag</key>
		<dict>
			<key>begin</key>
			<string>([\w.#_-]+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.slim</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-stuff</string>
				</dict>
			</array>
		</dict>
		<key>rubyline</key>
		<dict>
			<key>begin</key>
			<string>=='|='|==|=|-</string>
			<key>contentName</key>
			<string>source.ruby.embedded.slim</string>
			<key>end</key>
			<string>((do|\{)( \|[^|]+\|)?)$|[^\\]$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>source.ruby.embedded.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.ruby.start-block</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.line.ruby.slim</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Hack to let ruby comments work in this context properly</string>
					<key>match</key>
					<string>#.*$</string>
					<key>name</key>
					<string>comment.line.number-sign.ruby</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.ruby.rails</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#continuation</string>
				</dict>
			</array>
		</dict>
		<key>string-double-quoted</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.html</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.toc-list.id.html</string>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#embedded-ruby</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#entities</string>
				</dict>
			</array>
		</dict>
		<key>string-single-quoted</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.html</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.toc-list.id.html</string>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#embedded-ruby</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#entities</string>
				</dict>
			</array>
		</dict>
		<key>tag-id-attribute</key>
		<dict>
			<key>begin</key>
			<string>\b(id)\b\s*(=)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.id.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;='|")</string>
			<key>name</key>
			<string>meta.attribute-with-value.id.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string-double-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-single-quoted</string>
				</dict>
			</array>
		</dict>
		<key>tag-stuff</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline-html-tag</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#normal-html-tag</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag-id-attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interpolated-ruby</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#delimited-ruby-a</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#delimited-ruby-b</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#delimited-ruby-c</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rubyline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded-ruby</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.slim</string>
	<key>uuid</key>
	<string>36302CC1-1E76-4910-B7B6-F1915EBBA0D3</string>
</dict>
</plist>
