#!/bin/sh

CALENDAR=☼

WIDTH=${1}

SMALL=80
MEDIUM=107
LARGE=125
X_LARGE=150

if [ "$WIDTH" -gt "$X_LARGE" ]; then
  MPD="#[fg=colour81]♪ #(~/bin/now_playing.sh)"
  BATTERY="#(~/bin/battery.sh)"
  date_colour='colour41'
fi

if [ "$WIDTH" -ge "$LARGE" ]; then
  DATE="#[fg=colour255,bg=colour241,bold] $CALENDAR $(date +'%a %m-%d-%y')"
fi

if [ "$WIDTH" -ge "$MEDIUM" ]; then
  TIME="#[fg=colour255,bg=colour241,bold] $(date +'%H:%M:%S')"
fi

if [ "$WIDTH" -ge "$SMALL" ]; then
  CLEAR=""
fi

echo "$MPD $BATTERY $DATE $TIME " | sed 's/ *$/ /g'