# Customize to your needs...
export PATH="$HOME/.dotfiles/functions:$PATH"
export PATH="/usr/local/share/npm/bin:$PATH"
export PATH="/usr/bin:$PATH"
export PATH="/bin:$PATH"
export PATH="/usr/sbin:$PATH"
export PATH="/sbin:$PATH"
export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"
export PATH="$PATH:$ANDROID_HOME/tools"
export PATH="$PATH:$ANDROID_HOME/platform-tools"
export PATH="$HOME/.yarn/bin:$PATH"
# export PATH="$HOME/.composer/vendor/bin:$PATH"

# export PATH="$HOME/.pyenv/shims:$PATH"
# export PATH="$HOME/.rbenv/shims:$PATH"
