# === Theme: Powerlevel10k ===
#
# Normally Oh My Zsh loads the theme via ZSH_THEME=powerlevel10k/powerlevel10k
# (see zsh/zshrc.symlink), cloned into ~/.oh-my-zsh/custom/themes/powerlevel10k.
#
# This block is a FALLBACK: if OMZ didn't load p10k (e.g. it isn't installed
# yet), source the theme directly from the first location that exists so you
# still get a usable prompt. The `p10k` function only exists once the theme is
# loaded, so we use it to detect whether the fallback is needed.
if ! (( $+functions[p10k] )); then
  for _p10k_theme in \
    "$HOME/.oh-my-zsh/custom/themes/powerlevel10k/powerlevel10k.zsh-theme" \
    /opt/homebrew/share/powerlevel10k/powerlevel10k.zsh-theme \
    /usr/local/share/powerlevel10k/powerlevel10k.zsh-theme
  do
    if [[ -r "$_p10k_theme" ]]; then
      source "$_p10k_theme"
      break
    fi
  done
  unset _p10k_theme
fi

# Personal customizations generated by `p10k configure`.
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh
